### ISSUE TITLE
Indie signup / Future

### ISSUE THREAD

**Issue by notxt** [zachcalvert/the_ape_theater#2]
Hey! It's michael :stuck_out_tongue: 

I had an idea that we could add a link to the indie sign up or even put a form on the site and hit the api - ( maybe v1; v2 ) - thinking I can put in a PR for it if you're into it

Also, are there things you're still wanting to do with the site? Curious if want help with any of that. Might take me a minute to get up and running - ( mostly do Node ) - I've messed around with py scripts by haven't done a lot of making sites with it

thanks!
michael

**Comment by zachcalvert** [comment]
Yo yo! yea that would be sick. I'll add a guide to get local development set up in the README. that way you can run the site locally and get a view into how things are wired up.

The indie sign up form is a great idea. I need add couple more forms too (request corporate improv, general questions, etc). Maybe we can design one well and pattern match off that.

**Comment by notxt** [comment]
Workin' on getting it spun up and run into a dep issue that I'm thinking _might_ be my python version ... ?

```
Collecting idna==2.6 (from -r requirements.txt (line 27))
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting ipython==6.2.1 (from -r requirements.txt (line 28))
  Could not find a version that satisfies the requirement ipython==6.2.1 (from -r requirements.txt (line 28)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0)
No matching distribution found for ipython==6.2.1 (from -r requirements.txt (line 28))
michaels-MBP:the_ape notxt$ python -V
Python 2.7.10
```

What py version are you on?

**Comment by zachcalvert** [comment]
Good call yea I forgot to add that info to the requirements. The project is written to run on python-3.6.4. (yay for future ape devs)
